export const iconMap: Record<string, string> = {
  'code': '💻',
  'smartphone': '📱',
  'pen-tool': '🎨',
  'trending-up': '📈',
  'file-text': '✍️',
  'film': '🎬',
  'cpu': '🤖',
  'dollar-sign': '💰',
  'briefcase': '⚖️',
  'headphones': '🎧',
  'camera': '📷',
  'globe': '🌐',
  'tool': '🔧',
  'bar-chart': '📊',
  'music': '🎵',
};

export const ghanaFallbackCats = [
  { id: 'tech', icon: 'code', name: 'IT & Tech', description: 'Web Dev, App Dev, Digital Marketing', slug: 'it-tech' },
  { id: 'design', icon: 'pen-tool', name: 'Creative Arts', description: 'Graphics, Photography, Video', slug: 'creative-arts' },
  { id: 'trades', icon: 'tool', name: 'Skilled Trades', description: 'Carpenter, Plumber, Electrician', slug: 'skilled-trades' },
  { id: 'health', icon: 'headphones', name: 'Health & Wellness', description: 'Nurse, Physio, Fitness Coach', slug: 'health-wellness' },
  { id: 'build', icon: 'briefcase', name: 'Construction', description: 'Builder, Architect, Surveyor', slug: 'construction' },
  { id: 'edu', icon: 'file-text', name: 'Education & Tutoring', description: 'Teacher, Music, Art Instructor', slug: 'education' },
  { id: 'hosp', icon: 'bar-chart', name: 'Hospitality', description: 'Chef, Event Planner, Driver', slug: 'hospitality' },
  { id: 'biz', icon: 'dollar-sign', name: 'Business Services', description: 'Accountant, Consultant, Admin', slug: 'business' },
  { id: 'farm', icon: 'globe', name: 'Agriculture', description: 'Farmer, Agri-tech, Livestock', slug: 'agriculture' },
  { id: 'other', icon: 'trending-up', name: 'Others', description: 'Delivery, Security, Handyman', slug: 'others' },
];

export const testimonialFallbacks = [
  { first_name: 'Kwame', last_name: 'Asante', comment: "I'm a painter and GigGhana changed my life — I now get 5 jobs per week from clients I never could have reached before!", rating_overall: 5, role: 'provider', location: 'Accra', avatar: '' },
  { first_name: 'Abena', last_name: 'Mensah', comment: "As a nurse, I now offer home care through GigGhana. The platform is safe and payments always come on time via MoMo.", rating_overall: 5, role: 'provider', location: 'Kumasi', avatar: '' },
  { first_name: 'Kofi', last_name: 'Boateng', comment: "Carpenters like me now get long-term contracts. GigGhana verified my skills and clients trust me immediately.", rating_overall: 5, role: 'provider', location: 'Takoradi', avatar: '' },
  { first_name: 'Ama', last_name: 'Owusu', comment: "Finding a reliable electrician used to be a nightmare. Now I hire through GigGhana in minutes and the escrow keeps me safe.", rating_overall: 5, role: 'client', location: 'Accra', avatar: '' },
];

export const fallbackRecentJobs = [
  {
    id: 101,
    title: 'Interior Renovation & Modern POP Ceiling for 4-Bedroom Villa',
    description: 'Looking for a certified Ghanaian interior plasterer/artisan to design and install custom POP ceilings with embedded LED ambient coving in Airport Hills.',
    budget_min: 4500,
    budget_max: 6000,
    budget_type: 'fixed',
    is_urgent: 1,
    is_featured: 1,
    proposal_count: 4,
    location: 'Airport Hills, Accra',
    cat_name: 'Creative Arts',
    cat_icon: 'pen-tool',
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    first_name: 'Emmanuel',
    last_name: 'Agyeman',
  },
  {
    id: 102,
    title: 'Full-Stack Next.js 15 & Mobile Money (MoMo) Escrow Web Platform',
    description: 'Seeking an expert Ghanaian TypeScript developer to build a high-performance marketplace API with Paystack webhook processing and automated sub-60s MoMo payouts.',
    budget_min: 8500,
    budget_max: 12000,
    budget_type: 'fixed',
    is_urgent: 0,
    is_featured: 1,
    proposal_count: 7,
    location: 'East Legon, Accra',
    cat_name: 'IT & Tech',
    cat_icon: 'code',
    created_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    first_name: 'Selorm',
    last_name: 'Klutse',
  },
  {
    id: 103,
    title: '15kVA Commercial Solar Inverter & Hybrid Storage Installation',
    description: 'Require a certified renewable energy electrician to install a 15kVA 3-phase hybrid solar power system with lithium batteries for our logistics hub.',
    budget_min: 14000,
    budget_max: 18500,
    budget_type: 'fixed',
    is_urgent: 1,
    is_featured: 0,
    proposal_count: 3,
    location: 'Kumasi Central, Ashanti',
    cat_name: 'Skilled Trades',
    cat_icon: 'tool',
    created_at: new Date(Date.now() - 130 * 60 * 1000).toISOString(),
    first_name: 'Kwabena',
    last_name: 'Osei',
  },
  {
    id: 104,
    title: 'Architectural 3D Structural Modeling & Municipality Permit Drawings',
    description: 'Need a registered Ghanaian architect or structural draftsman to produce 3D isometric renderings and approved permit drawings for a commercial plaza in Takoradi.',
    budget_min: 5200,
    budget_max: 7500,
    budget_type: 'fixed',
    is_urgent: 0,
    is_featured: 1,
    proposal_count: 5,
    location: 'Takoradi, Western',
    cat_name: 'Construction',
    cat_icon: 'briefcase',
    created_at: new Date(Date.now() - 210 * 60 * 1000).toISOString(),
    first_name: 'Nana',
    last_name: 'Yeboah',
  },
  {
    id: 105,
    title: 'Commercial Restaurant Kitchen Plumbing & Grease Trap System',
    description: 'Licensed master plumber needed to re-pipe industrial drainage and connect high-pressure supply lines for a newly opened eatery in Tema Community 1.',
    budget_min: 3200,
    budget_max: 4500,
    budget_type: 'fixed',
    is_urgent: 1,
    is_featured: 0,
    proposal_count: 2,
    location: 'Tema Comm. 1, Greater Accra',
    cat_name: 'Skilled Trades',
    cat_icon: 'tool',
    created_at: new Date(Date.now() - 320 * 60 * 1000).toISOString(),
    first_name: 'Ekow',
    last_name: 'Baidoo',
  },
  {
    id: 106,
    title: 'Brand Identity, Export Packaging & Label Design for Cocoa Product',
    description: 'Graphic designer specializing in premium FMCG packaging to craft export-ready pouch labels with Ghana FDA & barcode compliance guidelines.',
    budget_min: 2800,
    budget_max: 3900,
    budget_type: 'fixed',
    is_urgent: 0,
    is_featured: 0,
    proposal_count: 6,
    location: 'Cape Coast, Central',
    cat_name: 'Creative Arts',
    cat_icon: 'pen-tool',
    created_at: new Date(Date.now() - 480 * 60 * 1000).toISOString(),
    first_name: 'Akosua',
    last_name: 'Darko',
  },
];

export const fallbackFeaturedProviders = [
  {
    id: 1,
    user_id: 1,
    first_name: 'Kwame',
    last_name: 'Asante',
    tagline: 'Master POP Ceiling Designer & Decorative Interior Plasterer',
    bio: 'Specializes in luxury acoustic ceilings, concealed LED coves, and custom 3D wall mouldings for residential villas and corporate offices.',
    cat_name: 'Creative Arts',
    cat_icon: 'pen-tool',
    location: 'Airport Hills, Accra',
    avatar: '/images/occupations/interior_designer.jpg',
    is_verified: 1,
    badge: '⭐ Premium Master',
    rating_avg: 5.0,
    rating_count: 48,
    completed_jobs: 42,
    hourly_rate: 95,
    skill_names: 'POP Ceilings|Interior Lighting|Wall Moulding',
    availability: 'full_time',
  },
  {
    id: 2,
    user_id: 2,
    first_name: 'Nana Kwabena',
    last_name: 'Osei',
    tagline: 'Certified Renewable Energy & 3-Phase Solar Inverter Engineer',
    bio: 'Over 8 years experience designing and commissioning off-grid hybrid lithium solar power systems for logistics facilities and luxury estates.',
    cat_name: 'Skilled Trades',
    cat_icon: 'tool',
    location: 'Kumasi Central, Ashanti',
    avatar: '/images/occupations/electrician.jpg',
    is_verified: 1,
    badge: '⭐ Premium Pro',
    rating_avg: 4.9,
    rating_count: 36,
    completed_jobs: 29,
    hourly_rate: 80,
    skill_names: 'Solar PV Systems|High-Voltage Wiring|Battery Backup',
    availability: 'full_time',
  },
  {
    id: 3,
    user_id: 3,
    first_name: 'Abena',
    last_name: 'Frimpong',
    tagline: 'Lead Full-Stack TypeScript & Next.js 15 Web/Mobile Architect',
    bio: 'Builds high-concurrency fintech platforms, automated MoMo escrow webhooks, and sub-second Next.js web applications.',
    cat_name: 'IT & Tech',
    cat_icon: 'code',
    location: 'East Legon, Accra',
    avatar: '/images/occupations/software_dev.jpg',
    is_verified: 1,
    badge: '👑 Elite Architect',
    rating_avg: 5.0,
    rating_count: 62,
    completed_jobs: 54,
    hourly_rate: 120,
    skill_names: 'Next.js 15|TypeScript|MoMo API Integration',
    availability: 'full_time',
  },
  {
    id: 4,
    user_id: 4,
    first_name: 'Kofi Mensah',
    last_name: 'Boateng',
    tagline: 'Master Hardwood Artisan & Custom Joinery Specialist',
    bio: 'Crafts bespoke mahogany dining sets, acoustic executive office furniture, and precision architectural cabinetry.',
    cat_name: 'Skilled Trades',
    cat_icon: 'tool',
    location: 'Spintex Road, Accra',
    avatar: '/images/occupations/carpenter.jpg',
    is_verified: 1,
    badge: '⭐ Verified Master',
    rating_avg: 4.9,
    rating_count: 31,
    completed_jobs: 27,
    hourly_rate: 75,
    skill_names: 'Mahogany Joinery|Cabinetry|Wood Finishing',
    availability: 'full_time',
  },
  {
    id: 5,
    user_id: 5,
    first_name: 'Akosua',
    last_name: 'Darko',
    tagline: 'Senior FMCG Brand Identity & Export Packaging Designer',
    bio: 'Award-winning brand designer creating export-ready food packaging, Ghana FDA-compliant labels, and premium corporate identities.',
    cat_name: 'Creative Arts',
    cat_icon: 'pen-tool',
    location: 'Cape Coast, Central',
    avatar: '/images/occupations/executive.jpg',
    is_verified: 1,
    badge: '⭐ Premium Designer',
    rating_avg: 5.0,
    rating_count: 29,
    completed_jobs: 23,
    hourly_rate: 85,
    skill_names: 'FMCG Packaging|Brand Identity|FDA Guidelines',
    availability: 'full_time',
  },
  {
    id: 6,
    user_id: 6,
    first_name: 'Ekow',
    last_name: 'Baidoo',
    tagline: 'Licensed Industrial & High-Pressure Plumbing Contractor',
    bio: 'Certified master plumber handling industrial piping, smart drainage systems, automated water pumps, and grease traps.',
    cat_name: 'Skilled Trades',
    cat_icon: 'tool',
    location: 'Tema Comm. 1, Greater Accra',
    avatar: '/images/occupations/plumber.jpg',
    is_verified: 1,
    badge: '✓ Verified Specialist',
    rating_avg: 4.8,
    rating_count: 24,
    completed_jobs: 21,
    hourly_rate: 70,
    skill_names: 'Industrial Plumbing|Pressure Pumps|Drainage Systems',
    availability: 'full_time',
  },
  {
    id: 7,
    user_id: 7,
    first_name: 'Emmanuel',
    last_name: 'Yeboah',
    tagline: 'Registered Structural Draftsman & 3D Architectural Modeler',
    bio: 'Produces municipality-approved 3D architectural drawings, isometric renders, and structural permit documentation across Ghana.',
    cat_name: 'Construction',
    cat_icon: 'briefcase',
    location: 'Takoradi, Western',
    avatar: '/images/occupations/architect.jpg',
    is_verified: 1,
    badge: '👑 Master Guild',
    rating_avg: 5.0,
    rating_count: 38,
    completed_jobs: 35,
    hourly_rate: 90,
    skill_names: 'Revit 3D|AutoCAD Permitting|Structural Modeling',
    availability: 'full_time',
  },
  {
    id: 8,
    user_id: 8,
    first_name: 'Dr. Selorm',
    last_name: 'Klutse',
    tagline: 'Senior Physiotherapist & Ergonomic Workspace Consultant',
    bio: 'Provides private physical therapy, corporate ergonomic health audits, and sports rehabilitation for executives and athletes.',
    cat_name: 'Health & Wellness',
    cat_icon: 'headphones',
    location: 'Cantonments, Accra',
    avatar: '/images/occupations/tech_hub.jpg',
    is_verified: 1,
    badge: '⭐ Premium Clinical',
    rating_avg: 5.0,
    rating_count: 41,
    completed_jobs: 39,
    hourly_rate: 110,
    skill_names: 'Physical Therapy|Ergonomics|Sports Rehab',
    availability: 'full_time',
  }
];

export interface LandingData {
  stats: {
    providers: number;
    jobs: number;
    completed: number;
    clients: number;
    earnings: number;
  };
  categories: Array<{
    id: string | number;
    name: string;
    slug?: string;
    icon: string;
    description?: string;
  }>;
  featured: any[];
  matchedProviders: any[];
  recentJobs: any[];
  liveJobs: any[];
  earningsData: number[];
  earningsTotal: number;
  reviews: any[];
}
